'use client';

import React, { useState } from 'react';
import api from '@/lib/api';

export default function SecuritySettingsPage() {
  const [loading, setLoading] = useState(false);
  const [qrCodeSvg, setQrCodeSvg] = useState('');
  const [recoveryCodes, setRecoveryCodes] = useState<string[]>([]);
  const [verificationCode, setVerificationCode] = useState('');
  const [isVerified, setIsVerified] = useState(false);
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');

  const handleEnable2FA = async () => {
    setLoading(true);
    setError('');
    setMessage('');
    try {
      const res = await api.post('/profile/2fa/enable');
      setQrCodeSvg(res.data.qr_code_svg);
      setRecoveryCodes(res.data.recovery_codes);
    } catch (err: any) {
      setError(err.response?.data?.message || 'Failed to initialize 2FA.');
    } finally {
      setLoading(false);
    }
  };

  const handleVerify2FA = async () => {
    if (!verificationCode.trim()) return setError('Please enter the 6-digit code.');
    setLoading(true);
    setError('');
    setMessage('');
    try {
      const res = await api.post('/profile/2fa/verify', { code: verificationCode.trim() });
      setMessage(res.data.message || 'Two-Factor Authentication enabled successfully.');
      setIsVerified(true);
    } catch (err: any) {
      setError(err.response?.data?.message || 'Invalid code. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleCopyCodes = () => {
    navigator.clipboard.writeText(recoveryCodes.join('\n'));
    alert('Backup codes copied to clipboard!');
  };

  const handleDownloadCodes = () => {
    const element = document.createElement("a");
    const file = new Blob([recoveryCodes.join('\n')], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = "fastpos-backup-codes.txt";
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="p-6 max-w-4xl mx-auto w-full">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-foreground">Security Settings</h1>
        <p className="text-text-muted mt-2">Manage your account security and two-factor authentication.</p>
      </div>

      <div className="bg-card border border-border rounded-2xl shadow-sm p-6 mb-8">
        <h2 className="text-xl font-semibold text-foreground mb-4">Two-Factor Authentication (2FA)</h2>
        <p className="text-sm text-text-muted mb-6">
          Add an extra layer of security to your account. Once enabled, you'll be prompted to enter a 6-digit code from your authenticator app during login.
        </p>

        {error && (
          <div className="bg-danger/10 border border-danger/30 text-danger text-sm px-4 py-3 rounded-xl mb-6">
            {error}
          </div>
        )}
        {message && (
          <div className="bg-success/10 border border-success/30 text-success text-sm px-4 py-3 rounded-xl mb-6">
            {message}
          </div>
        )}

        {!qrCodeSvg && !isVerified && (
          <button
            onClick={handleEnable2FA}
            disabled={loading}
            className="bg-primary text-white font-semibold py-2.5 px-6 rounded-xl hover:bg-primary/90 transition-colors shadow-sm"
          >
            {loading ? 'Initializing...' : 'Enable Two-Factor Authentication'}
          </button>
        )}

        {qrCodeSvg && !isVerified && (
          <div className="border border-border rounded-xl p-6 bg-background/50">
            <h3 className="text-lg font-medium text-foreground mb-4">1. Scan this QR Code</h3>
            <p className="text-sm text-text-muted mb-4">
              Open your authenticator app (like Google Authenticator or Microsoft Authenticator) and scan the QR code below.
            </p>
            <div 
              className="bg-white p-4 inline-block rounded-xl mb-6 shadow-sm border border-border"
              dangerouslySetInnerHTML={{ __html: qrCodeSvg }}
            />
            
            <h3 className="text-lg font-medium text-foreground mb-4">2. Verify Setup</h3>
            <p className="text-sm text-text-muted mb-4">
              Enter the 6-digit code generated by your app to verify and complete the setup.
            </p>
            <div className="flex gap-4 max-w-sm">
              <input
                type="text"
                value={verificationCode}
                onChange={(e) => setVerificationCode(e.target.value)}
                placeholder="000000"
                maxLength={6}
                className="flex-1 bg-background border border-border rounded-xl px-4 py-2.5 text-foreground font-mono tracking-widest text-center focus:ring-2 focus:ring-primary/20 focus:border-primary outline-none transition-all"
              />
              <button
                onClick={handleVerify2FA}
                disabled={loading || verificationCode.length < 6}
                className="bg-primary text-white font-semibold py-2.5 px-6 rounded-xl hover:bg-primary/90 transition-colors disabled:opacity-50 shadow-sm"
              >
                {loading ? 'Verifying...' : 'Verify'}
              </button>
            </div>
          </div>
        )}

        {isVerified && recoveryCodes.length > 0 && (
          <div className="border border-success/30 bg-success/5 rounded-xl p-6">
            <h3 className="text-lg font-semibold text-foreground mb-2 flex items-center gap-2">
              <span className="text-success">✓</span> 2FA Enabled Successfully
            </h3>
            <p className="text-sm text-text-muted mb-6">
              Please save these backup codes in a secure location. You can use them to access your account if you lose your device. Each code can only be used once.
            </p>
            
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-6">
              {recoveryCodes.map((code, idx) => (
                <div key={idx} className="bg-background border border-border rounded-lg p-3 text-center font-mono text-sm tracking-wider shadow-sm">
                  {code}
                </div>
              ))}
            </div>

            <div className="flex gap-4">
              <button
                onClick={handleCopyCodes}
                className="flex-1 sm:flex-none bg-background border border-border text-foreground font-medium py-2.5 px-6 rounded-xl hover:bg-muted transition-colors"
              >
                Copy to Clipboard
              </button>
              <button
                onClick={handleDownloadCodes}
                className="flex-1 sm:flex-none bg-primary text-white font-medium py-2.5 px-6 rounded-xl hover:bg-primary/90 transition-colors shadow-sm"
              >
                Download as TXT
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
